### ISSUE TITLE
Feature Request: `redirector_ui.uc.js` 配置文件路径支持 Linux 等系统

### ISSUE THREAD

**Issue by Firef0x** [harv/userChromeJS#1]
@Harv 大神，您好！ :smiley: 

首先感谢您编写并维护 `redirector_ui.uc.js` 脚本！ :+1: 
### 问题描述

[redirector_ui.uc.js 第185行](https://github.com/Harv/userChromeJS/blob/master/redirector_ui.uc.js#L185) 中定义的菜单配置文件路径中包含了 `\\` 字符，在 Linux 等以 `/` 作为路径分隔符的系统中会导致识别失败，无法加载配置文件。

目前我只能通过修改为：

``` javascript
this.rulesFolder = "local";
this.rulesFile = "_redirector.js";
......
aFile.appendRelativePath(this.rulesFolder);
aFile.appendRelativePath(this.rulesFile);
```

来支持 Linux 系统的路径。
### 参考资料

建议参照之前我提出另一个相似的问题 [Feature Request: ShowFlagS配置文件路径支持Linux等系统](https://github.com/feiruo/userChromeJS/issues/2) 时 ，@feiruo 大神给出的解决方案：
- 粗糙支持各系统路径 https://github.com/feiruo/userChromeJS/commit/8b3eb46770b0fdb338e9438fa12de16166d1d016
- 完善路径支持 https://github.com/feiruo/userChromeJS/commit/08bddd6aaf2d83de6173013f751431b146807acf
- 完善各OS路径支持 https://github.com/feiruo/userChromeJS/commit/612a2e11de742b04f20d6ab881aa7ed2a166c31b

此致！ :bow:

**Comment by harv** [comment]
尝试修复了下 c0d83edee71a718bfdff8e54d217d93dadb677e0

**Comment by Firef0x** [comment]
测试可用！感谢大神！ :rose: 抱歉我忘了及时反馈了。

在此提个小小的建议， [第 64 行](https://github.com/Harv/userChromeJS/blob/master/redirector_ui.uc.js#L64) 及 [第 277 行](https://github.com/Harv/userChromeJS/blob/master/redirector_ui.uc.js#L277) 其实可以改成这种形式：

``` javascript
let aFile = FileUtils.getFile("UChrm", this.redirector.rulesFile.split('\\'), false);
```

这样可以保持 [第 228 行](https://github.com/Harv/userChromeJS/blob/master/redirector_ui.uc.js#L228) 配置变量 

``` javascript
this.rulesFile = "local\\_redirector.js";
```

的形式不变，对原有用户影响最小。

另外个人觉得把能够自定义的配置变量 `this.rulesFile` 尽量放到文件最前面几十行比较好，类似此提交 https://github.com/Harv/userChromeJS/commit/9d580ae5e61aa219a919cb0e9562de7d2c5fd188 之前的做法一样。

此致！ :bow:
