### ISSUE TITLE
最新的redirector不能读取规则

### ISSUE THREAD

**Issue by zousiyu1995** [harv/userChromeJS#3]
![2016-06-14_143804](https://cloud.githubusercontent.com/assets/7608449/16033258/a2bee138-323d-11e6-89af-26dfb3e05b1c.png)
![2016-06-14_143839](https://cloud.githubusercontent.com/assets/7608449/16033273/bc1b837a-323d-11e6-8edf-1a0a0a1c9657.png)
按规定放的规则文件，并不能读取

**Comment by harv** [comment]
能否提供 Ctrl + Shift + J 中的错误信息？

**Comment by zousiyu1995** [comment]
![2016-06-24_134736](https://cloud.githubusercontent.com/assets/7608449/16329066/91c6aa50-3a12-11e6-99e1-0ba5af746a3c.png)

**Comment by harv** [comment]
没有发现和 redirector_ui.uc.js 有关的错误信息。
_redirector.js 格式是否正确？

**Comment by zousiyu1995** [comment]
仔细检查了一下，规则有问题，现在好了
