### ISSUE TITLE
Redirector 1.5.5.4?

### ISSUE THREAD

**Issue by dupontjoy** [harv/userChromeJS#4]
1. 更新了什么內容? 
2. 能不能直接做个菜单版?
   用这个脚本很久了, 复杂点的是在扩展里建规则, 然后搬到脚本
   扩展版的规则文件格式太乱, 还是脚本方便

**Comment by harv** [comment]
1. 移除了for each这个废弃的特性
2. 已增加菜单版 f39d06e88d2afa34ea32244ff93eb1ae9a7e5b1c

**Comment by dupontjoy** [comment]
太感谢啦

dupontjoy@163.com

From: Hao
Date: 2016-07-11 13:26
To: harv/userChromeJS
CC: 玄清介; Author
Subject: Re: [harv/userChromeJS] Redirector 1.5.5.4? (#4)
移除了for each这个废弃的特性
已增加菜单版 f39d06e
