### ISSUE TITLE
求修改openNewTab.uc.js

### ISSUE THREAD

**Issue by Alanomn** [harv/userChromeJS#5]
这个脚本终于解决了我书签历史搜索栏新标签打开的问题，太棒了······
但是并没有地址栏输入结果新标签打开，试过各种脚本，都失效了，火狐52.0.2

**Comment by Alanomn** [comment]
openNewTab.uc.js 新1.3版，不但地址栏在当前页打开，历史和书签也变成当前页打开了。
火狐52.0.2新配置，userChromeJS扩展（mozdev.org原版）+userChrome.js（Alice0775原版）+rebuild_userChrome.uc.xul（Y大修改版）

**Comment by Alanomn** [comment]
好像就 超级标签模式(Super Tab Mode)扩展 正常
https://addons.mozilla.org/zh-CN/firefox/addon/super-tab-mode/?src=api

**Comment by harv** [comment]
我的错。现在应该可以了，重新下载下。
记得将`var b_urlbar = false;`改成`var b_urlbar = true;`地址栏才能生效

**Comment by Alanomn** [comment]
非常感谢大神作者@-@
现在 历史书签（菜单、按钮、侧边栏、我的足迹），地址栏打开网址和关键字，搜索栏搜索关键字，都在新标签打开，
可以删除Super Tab Mode扩展了
呵呵
