### ISSUE TITLE
 redirector.uc.js

### ISSUE THREAD

**Issue by dezhavu** [harv/userChromeJS#9]
Hey mate,

Does it work for firefox 63?
I tried different combinations, but just cant get it to work..

Using userchrome.js setup from alice0775, put redirector.uc.js in \chrome\local folder (as it was shown in redirector_ui.uc.js)
Tried adding sample rule for http > https redirect to check if it works, but it doesnt..

https://www.upload.ee/image/9173441/2018-11-10_04h57_04.png

Pressing Edit in menu doesnt work either, I see no rules in the list if they should be there (i guess..)
https://www.upload.ee/image/9173448/2018-11-10_05h01_20.png

What am I doing wrong? 
My setup: firefox 63  x64 (multiprocess) , win10

**Comment by harv** [comment]
Did you put `_redirector.js` in \chrome\local?

**Comment by dezhavu** [comment]
Works! Thanks!
Didn't understand how to set it up.. (thought those 2 files were enough)
Should I duplicate rules to both _redirector.js and redirector.uc.js  ? I have 4 rules now and all show as "undefined" in the menu, but they work at least.

One more thing - Reload leads to
TypeError: this.redirector.clearCache is not a function[Learn More] redirector_ui.uc.js:243:17 

Again thanks!

**Comment by harv** [comment]
>  I have 4 rules now and all show as "undefined" in the menu

You should supply a "name" for each rule, like https://github.com/harv/userChromeJS/blob/a267f5dc95468f4ff037531b592a1fabcbab1e66/_redirector.js#L2
